# Turn a coord delta into a direction
# 0,0 is the top left of the map
DIRECTION_MAP = {
    (0, -1): 'up',
    (0, 1): 'down',
    (-1, 0): 'left',
    (1, 0): 'right'
}

TRAIT_OPPORTUNISTIC = 'opp'
TRAIT_AGGRESSIVE = 'agg'
TRAIT_GLUTTONOUS = 'glu'
TRAIT_INSECURE = 'ins'

DNA = [
    10,     # BASE_COST
    100,    # HEAD_DANGER_COST
    2,      # TRAP_SIZE_MULTIPLIER
    400,    # TRAP_DANGER_COST
    20,     # WALL_DANGER_COST
    -5,     # TRAPPED_SELF_ADJACENT_COST
    -10,    # TRAPPED_WALL_ADJACENT_COST
    100,    # MAX_COST_CONSIDERED_SAFE
    30,     # PECKISH_THRESHOLD
    10,     # STARVING_THRESHOLD
    20      # MAX_OPPORTUNISTIC_EAT_COST
]

# Algorithm constants
BASE_COST = DNA[0]
HEAD_DANGER_COST = DNA[1]
TRAP_SIZE_MULTIPLIER = DNA[2]
TRAP_DANGER_COST = DNA[3]
WALL_DANGER_COST = DNA[4]
TRAPPED_SELF_ADJACENT_COST = DNA[5]
TRAPPED_WALL_ADJACENT_COST = DNA[6]
MAX_COST_CONSIDERED_SAFE = DNA[7]
PECKISH_THRESHOLD = DNA[8]
STARVING_THRESHOLD = DNA[9]
MAX_OPPORTUNISTIC_EAT_COST = DNA[10]